version: "3.7"
services:
    airrun:
       image: docker.centurionx.net/airrun:stable
       privileged: true
       logging:
        driver: none
       deploy:
         restart_policy:
             condition: on-failure
       volumes:
         - /dev/bus/usb:/dev/bus/usb
       network_mode: "host"
    connect:
       image: docker.centurionx.net/airconnect
       logging:
        driver: none
       deploy:
         restart_policy:
             condition: any
       network_mode: "host"

