version: "3.7"
services:
    airrun:
       image: airrun
       ports: 
         - 30005:30005
       privileged: true
       deploy:
         restart_policy:
             condition: on-failure
       volumes:
         - /dev/bus/usb:/dev/bus/usb
       network_mode: "host"
#       networks:
#         - host
#         - planesense
    connect:
       image: airconnect
       deploy:
         restart_policy:
             condition: any
       network_mode: "host"
#       networks:
#          - host
#         - planesense
#networks:
#    planesense: {}
